locale          : "en-US"
title           : "Kyeong-Jun Kim"
title_separator : "-"
name            : "Kyeong-Jun Kim"
description     : "Department of Sociology, Seoul National University"
url             : "https://kyeongjunkim.com"
baseurl         : ""
repository      : "kyeong-jun-kim/kyeong-jun-kim.github.io"

author:
  avatar        : "profile.jpg"
  name          : "Kyeong-Jun Kim (김경준)"
  bio           : "Ph.D. Candidate in Sociology"
  location      : "Seoul, South Korea"
  employer      : "Seoul National University"
  email         : "kj.kim@snu.ac.kr"
  googlescholar : "https://scholar.google.com/citations?user=0rgVPasAAAAJ&hl=ko"
  orcid         : "https://orcid.org/0000-0002-9476-2705"
  semantic      : "https://www.semanticscholar.org/author/Kyeong-Jun-Kim/2109953487"
  researchgate  : "https://www.researchgate.net/profile/Kyeong-Jun-Kim"
  scopus        : "https://www.scopus.com/authid/detail.uri?authorId=58018319200"
  publons       : "https://www.webofscience.com/wos/author/record/IVH-4819-2023"

publication_category:
  manuscripts(english):
    title: "Journal Articles (in English)"
  manuscripts(korean):
    title: "Journal Articles (in Korean)"

# Keep dated publications visible when an upcoming item is added.
future: true

include:
  - _pages

exclude:
  - .bundle
  - .devcontainer
  - .github
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - assets/js/plugins
  - Dockerfile
  - Gemfile
  - LICENSE
  - docker-compose.yaml
  - node_modules
  - package.json
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections:
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
